### PR TITLE
blog preview component

### LINKED ISSUE #599: [client] Add the latest 3 blog posts on the main page
[Link to specs](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2%3A2)
Create a component to display the preview of the latest 3 blog posts on the main page.
The preview should contain the `title` of the post and the `cover photo`.

Screenshot 2021-03-08 at 16 15 20

### PR DESCRIPTION
**Pull request by myshy93**
### What does it fix?

Implemented blog preview component for the main page. Displays latest 3 blog posts,

Closes #599 

### How has it been tested?

Manual test:

*Desktop:*
image
image

*Mobile:*

image

### CODE REVIEW

**Comment by tudoramariei** [comment]
A few issues I found:
- previews should open the blog post when clicked (e.g. clicking on Test time should take you [to the actual blog post](https://seismic-risc-gqinoxq03-code4romania.vercel.app/blog/test-time))
- all photos should be resized to fit; right now only tall photos are being resized while wide ones aren't (see the preview deployment, first two blog posts) 
- the title should be displayed on two lines if it is long enough and then stripped if it goes beyond that
- the last 3 posts should be returned, so please use the following query: `/api/v1/posts/?ordering=-published`

**Comment by myshy93** [comment]
fetch(`${POSTS_URL}/?ordering=-published`) is not ok?

**Comment by tudoramariei** [comment]
Yes, it's good. The blog posts displayed are the right ones.
Sorry, it seems I got confused.

**Comment by myshy93** [comment]
do not merge yet

**Comment by myshy93** [comment]
work done

**Review by razvanpavel — APPROVED** [review]

**Review by tudoramariei — APPROVED** [review]

**Pull request merged**
