### PR TITLE
Issue 95 | Create detailed building view

### LINKED ISSUE #95: [frontend] Create detailed building view
As a user, when I click on a building, I want to see a side-view on the right-hand side of the map where I can read all the details about the currently selected building, in order to understand the context in which it was marked as being a risk. 

As reference, use [the second mockup image](https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1).

### PR DESCRIPTION
**Pull request by vladplesu**
Closes #95 

- add building details component

### CODE REVIEW

**Comment by tudoramariei** [comment]
The UI looks good, there's just more thing I'd like to see but I'd first like to know if it would take too long to implement it.
I'd like if the building selection was reset once we've moved to another filter. Right now, I can select a building, move to a different filter, move back to the old filter and the building is still there. But I would like to have no other buildings selected when moving back to the old filter. 

Screen Recording 1080  2020-06-14 at 22 02 43

**Comment by vladplesu** [comment]
> 
> 
> The UI looks good, there's just more thing I'd like to see but I'd first like to know if it would take too long to implement it.
> I'd like if the building selection was reset once we've moved to another filter. Right now, I can select a building, move to a different filter, move back to the old filter and the building is still there. But I would like to have no other buildings selected when moving back to the old filter.
> 
> Screen Recording 1080 2020-06-14 at 22 02 43

It won't take long (not more than 1h). I`ll update the PR over the weekend.

**Comment by tudoramariei** [comment]
I'll come back to the previous comment and say that the behaviour seems to be the same. The map no persistence in between filters. **Still, that doesn't matter right now.**
Since it's not a bug introduced by these changes, this doesn't matter right now. I'll open a new issue for this matter and it will be handled there.

**Comment by tudoramariei** [comment]
There are quite a few issues with the responsiveness of the map. If the window is too narrow two things happen:
1. Not all the info fits on the screen
2. The pin is hidden behind the overlay

The exact thing happens on mobile. While I don't expect the pin to be visible anymore, the information still needs to be visible.

seismic mobile 2020-06-22 22_52_12

**Comment by vladplesu** [comment]
- [x] when changing filters map zooms on map markers and the building details drawer is closed
- [x] map is responsive
- [x] building details drawer is now smaller for mobile devices
- [x] when a marker is clicked the zoom is not centered on the marker and it will not be hidden by the building details drawer

The App fails to pass the test due to the `HereMapInteractive `component where Here Maps API is used. A solution would be to add a `setupTests.js` file and add a mock for the H class object:
```
window.H = {
  service: {
    Platform: class {
      constructor() {
        console.log('this is a mock constructor for Platform');
      }
      createDefaultLayers = jest.fn().mockImplementation(() => ({
        vector: {
          normal: {
            map: {},
          },
        },
      }));
    },
  },
}
``` 
Let me know if another solution can be used, in the mean time I`ll prepare the file and come back with another commit.

**Pull request merged**
