### PR TITLE
Map pins

### LINKED ISSUE #526: [client] Customize map markers by their category
Pins should have **different shapes** & **different colours** based on the risk category of the building they show. 

The customization should allow for the representation of 9 categories: 
> `U1`, `U2`, `U3`, `U4`, `RS I`, `RS II`, `RS III`, `RS IV`, `N/A`

🔗   [The location of the marker implementation is here](https://github.com/code4romania/seismic-risc/blob/develop/client/src/components/HereMapInteractive.js#L76)

### PR DESCRIPTION
**Pull request by myshy93**
Map marker customization for the representation of 9 categories:

`U1, U2, U3, U4, RS I, RS II, RS III, RS IV, N/A`

### What does it fix?

Closes #526 

### How has it been tested?
Render map with at least one building in each category.

### CODE REVIEW

**Comment by tudoramariei** [comment]
@myshy93 can you resolve the conflicts and squash your changes? The PR should be good to merge after that. 😄

**Comment by myshy93** [comment]
working on it

**Comment by myshy93** [comment]
ignore last commit, i still have work to do

**Comment by myshy93** [comment]
sorry for this mess, i will make another pull request

**Pull request closed without merging**
