### PR TITLE
Buildings API endpoints with partial info

### LINKED ISSUE #573: Create an API endpoint that returns partial info on buildings
Multiple views should be available for the buildings endpoints which should:
1. return for **all the buildings** only the `general_id`, `lat`, `lng`, and `risk_category` 
2. return for **one specific building** all the necessary fields (as it currently happens)

The downside is that this would require changes to the client makes individual requests for each building that is selected.

### PR DESCRIPTION
**Pull request by JustBeYou**
### What does it fix?
Listing and searching buildings return only part of the details.
The client loads full info on request. (see BuildingDetailsFragment)

Closes #573 

### How has it been tested?
Added unit tests. Manual testing on the frontend, the screenshots below.
seismic1
Screenshot from 2021-03-01 13-00-28

### CODE REVIEW

**Comment by JustBeYou** [comment]
Sorry for spamming with commits, but `black` is failing even if on my local machine everything is all right. 
```bash
(‿ˠ‿) ❯ ❯) black --line-length 80 --target-version py37 --exclude migrations --check ./api
All done! ✨ 🍰 ✨
33 files would be left unchanged.
```

**Comment by tudoramariei** [comment]
Make sure you have the right version of Black on your PC
Right now, it's testing with `black==20.8b1`

**Comment by JustBeYou** [comment]
Thank you. Should be fine now.

**Comment by tudoramariei** [comment]
@JustBeYou we merged some PRs and caused a few conflicts in your PR; we can merge the PR as soon as they're solved :)

**Review by tudoramariei — APPROVED** [review]

**Comment by JustBeYou** [comment]
@tudoramariei good to go :smiley:

**Pull request merged**
