### PR TITLE
tests: API tested entirely

### LINKED ISSUE #88: [api] Add tests to the pages api
Create a `api/tests/test_pages_api.py` file that tests the basic view functionality of the `pages` api. No need to test the create/update methods as those will be removed from the client facing api.

We use the [pytest](https://docs.pytest.org/en/latest/) testing framework, make sure you use of all its awesome features. :)

### LINKED ISSUE #89: [api] Add tests to the buildings api
Create a `api/tests/test_buildings_api.py` file that tests the basic CRUD functionality of the `buildings` api.

We used the [pytest](https://docs.pytest.org/en/latest/) testing framework, make sure you use of all its awesome features. :)

### LINKED ISSUE #110: [api] Add tests to the blog api
Create a api/tests/test_blog_api.py file that tests the basic read functionality of the blog api.

We used the pytest testing framework, make sure you use of all its awesome features. :)

### PR DESCRIPTION
**Pull request by JustBeYou**
Add tests for the entire API, code coverage almost 100%, except a few lines [here](https://github.com/code4romania/seismic-risc/blob/develop/api/pages/models.py#L81) (but I strongly believe that it's dead code). 

This PR should 
- fix #88 
- fix #89 
- fix #110 

It's my first contribution to Code4Romania, so I'll be glad to get a review 😄

### CODE REVIEW

**Comment by tudoramariei** [comment]
Hey, @JustBeYou!  Thanks a lot for the contribution. I didn't get to look over the code properly; I managed to have a quick look over the failing GitHub actions, though. Here are my comments for now:

It seems that the static analysis check is failing because you probably didn't format your code. You can do this by running this command from the project root:
`black --line-length 80 --target-version py37 --exclude migrations ./api`

Also, it seems that a test fails. We're using an SQLite database in testing, so the `SIMILARITY` method won't be available there. I'd like to keep that test, though skip it for now since it won't work unless in a development or production environment.

**Comment by JustBeYou** [comment]
Hi, @tudoramariei 
Sorry for not checking the CI in the first place. Now everything should be fixed. 
By the way, `black` also altered some other files, not just the tests, so I've added them in a separate commit so you could discard them if they are not necessary.

**Review by tudoramariei — APPROVED** [review]

**Comment by tudoramariei** [comment]
Thanks for the changes! I've merged them now.

I have some feedback regarding the workflow. In the future, make sure you **create a feature branch** and create a PR from that one and not from your `develop` branch.
You will now have to re-sync your `develop` branch with `--force` 😢 . The instructions from [the workflow document](https://github.com/code4romania/seismic-risc/blob/develop/.github/WORKFLOW.MD#doing-your-work) should clear some things out about how we work. If you need some help, though, let me know. 😄 

Also, you can join us on Slack if you want to get more involved in our projects.
https://tfsg.code4.ro/ro/hackday/

**Comment by JustBeYou** [comment]
Thanks for the feedback, Tudor!
I've already registered for the next hackday, can't wait to know more about your projects and get in touch with the team!

**Pull request merged**
